name : Deploy Nodejs Backend

on:
  push:
    branches:
      - main

jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      # - name: Create .env file
      #   run: echo "MONGO_ATLAS=${{ secrets.MONGO_ATLAS }}>.env"
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker image
        run: docker build -t ankit1030/cicdbackend .
      - name: Push image to Docker Hub
        run: docker push ankit1030/cicdbackend:latest  

  deploy:
    needs: build
    runs-on: self-hosted
    steps: 
      - name: Pull image from Docker Hub
        run: docker pull ankit1030/cicdbackend:latest
      - name: Delete Old Container
        run: docker rm -f nodejsBackend || true
      - name: Run docker Container
        run: docker run -d --init -p 4000:4000 --name nodejsBackend ankit1030/cicdbackend
    

  #  deploy:
  #   needs: build
  #   runs-on: self-hosted
  #   steps:
  #     - name: Pull image from docker hub
  #       run: docker pull integrationninjas/nodejs-app:latest
  #     - name: Delete old container
  #       run: docker rm -f nodejs-app-container  
  #     - name: Run docker container
  #       run: docker run -d -p 4000:4000 --name nodejs-app-container integrationninjas/nodejs-app   